### ISSUE TITLE
unable to find conda binary. is anaconda installed

### ISSUE THREAD

**Issue by beccawindell** [mikeyEcology/MLWIC#10]
I am stuck at the setup function. The error I get is: unable to find conda binary. is anaconda installed. I have tried every iteratation of the directory I can think of and scoured the locations inwhich anaconda and python are installed. I know where my ptython.exe file is but am unclear of what file I am looking for in terms of the conda_loc. I have installed anaconda. Tensorflow is also installed. Side bar: how important is it that one runs Python 3.6 vs 3.7? I have 3.7 installed.

**Comment by mikeyEcology** [comment]
Can you please post the code that you input and the code that is output by R? It should work on Python 3.7 as well. You can also try not specifying `conda_loc` and allow the function to try finding it for you.

**Comment by beccawindell** [comment]
Hi, thank you for your help. 

Here is the input code (using Python 3.6.7):
setup(python_loc = "C:/Users/Becca/Anaconda3/Python36/", conda_loc = "C:/Users/Becca/Anaconda3/Scripts/")

And output: code:
setup(python_loc = "C:/Users/Becca/Anaconda3/Python36/", conda_loc = "C:/Users/Becca/Anaconda3/Scripts/")
Error: Unable to find conda binary. Is Anaconda installed?

The same output/error apply when I specificy the excecutables, and try the same with Python 3.7.1 that was downloaded with Anaconda:
setup(python_loc = "C:/Users/Becca/Anaconda3/Python36/python.exe", conda_loc = "C:/Users/Becca/Anaconda3/Scripts/conda.exe")
setup(python_loc = "C:/Users/Becca/Anaconda3/", conda_loc = "C:/Users/Becca/Anaconda3/Scripts/")
setup(python_loc = "C:/Users/Becca/Anaconda3/python.exe", conda_loc = "C:/Users/Becca/Anaconda3/Scripts/conda.exe")

**Comment by mikeyEcology** [comment]
Are you sure that Anaconda is stored in this location? This is not the typical location that it stores automatically when you download it on a Windows machine. Typically it is stored in a hidden folder called "ProgramData".
If Anaconda is in the directory you specified, you can try this:
`````
setup(python_loc = "C:/Users/Becca/Anaconda3/Python36/python", 
     conda_loc = "auto)
`````

**Comment by VwakeM** [comment]
Is it necessary to have Anaconda installed? Or Python will do? Thanks!
