### ISSUE TITLE
data_info - no such file or directory

### ISSUE THREAD

**Issue by tundraboyce** [mikeyEcology/MLWIC#14]
Hi, I am slowly making progress though I have hit an error where code seems unable to find the csv file for image labels. Code and error below - any help would be great. The file is right there in the same folder as the image folder

> classify(path_prefix = "C:/Users/Paul/Desktop/Image_processing/MLWIC_examples-master/images/", 
+          data_info = "C:/Users/Paul/Desktop/Image_processing/MLWIC_examples-master/image_labels.csv", 
+          model_dir = "C:/Users/Paul/Desktop/Image_processing", 
+          python_loc = "C:/Users/Paul/Anaconda3/", 
+          save_predictions = "C:/Users/Paul/Desktop/model_predictions.txt" 
+ )

C:\Users\Paul\ANACON~1\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "eval.py", line 129, in <module>
    main()
  File "eval.py", line 116, in main
    args.num_samples = sum(1 for line in open(args.data_info))
FileNotFoundError: [Errno 2] No such file or directory: 'data_info.csv'

Cheers,
Paul

**Comment by samsara604** [comment]
Hello,

I get the same error. Running Windows 10, tensorflow appears to be working, setup error with argparse and tensorflow in conflict.

I had some of the errors others have had but addressed them: not running on desktop, re-downloading example folder, not re-saving the csv file, etc.

I suspect it had something to do with the fact the csv file has Unix linebreaks so I tried re-creating the file in Windows and also re-naming it. No luck.

Any help is appreciated,

Cheers,

Stephen

**Comment by edbel22** [comment]
Hi, I am running into similar problems running on Windows 10 using the same code as Mickey. The only difference is I specify path to Python, not Anaconda:

classify(path_prefix = "C:/Users/ebelanger/Desktop/images", 
         data_info = "C:/Users/ebelanger/Desktop/image_labels.csv",
         model_dir = "C:/Users/ebelanger/Desktop", 
         python_loc = "C:/Users/ebelanger/AppData/Local/Programs/Python/Python36/", 
         save_predictions = "model_predictions.txt"
)

I get:
Traceback (most recent call last):
  File "eval.py", line 129, in <module>
    main()
  File "eval.py", line 116, in main
    args.num_samples = sum(1 for line in open(args.data_info))
FileNotFoundError: [Errno 2] No such file or directory: 'data_info.csv'

Similarly, it seems that data_info is having issue being found.

Any help would be appreciated (sorry I can't help you guys up there)!

Ed

**Comment by Nova-Scotia** [comment]
Hey all, see #13  I am adding details there which may be of use to you in a couple mins.

**Comment by samsara604** [comment]
Hi everyone, #13 solved my problem and I was able to run the classify function.

Thank you fabstp, Nova-Scotia, and christinamaiello!

**Comment by Nova-Scotia** [comment]
@tundraboyce , if #13  solved your issue, perhaps you could close this one? If you're still struggling, maybe I can help!

**Comment by tundraboyce** [comment]
@Nova-Scotia Hi! sorry for the delay, I was away from this for a couple of weeks. I have gone through #13 and seemed to have come full circle and am back at "FileNotFoundError: [Errno 2] No such file or directory: 'data_info.csv'". 

I have followed all the steps in #13 and seemed to get a bunch of different errors and then once I had the tensorflow version etc all right, I came back to the file not found error. 

Any suggestions?

**Comment by tundraboyce** [comment]
Well it finally got to work! The one step I missed was renaming the images_info.csv to data_info.csv, and now it's all working! 

Not sure which step in particular made it go but it sure seems like once that was changed, it went fine. 

Thanks @Nova-Scotia and everyone for persisting through it!

**Comment by Nova-Scotia** [comment]
That's great! Glad to hear it. Really great to have this community of people working together. Best of luck!
