### ISSUE TITLE
Where to find images used for training?

### ISSUE THREAD

**Issue by eap** [mikeyEcology/MLWIC#15]
In the draft paper describing this package/classifier you write;

"Images used for training and testing models and their classifications are available in a digital repository"

Would you be willing to go into a little more detail either here or in the Readme about how one could request access to your training set? For a personal project I'm looking to access some of the whitetail and mule deer images in order to (attempt to) create a "mature buck" classifier.

**Comment by Nova-Scotia** [comment]
Hi @eap , have you seen the ([non-draft) version](https://doi.org/10.1111/2041-210X.13120) of the paper? It has a link to the North American camera trap dataset listed in the data accessibility portion of the paper, near the end: 

> We provide the >3.7 million classified
> images as the North American Camera Trap Images (NACTI)
> dataset in the Labeled Information Library of Alexandria: Biology &
> Conservation (LILA:BC) digital repository 
> (available online at [http://lila.science/datasets/nacti](http://lila.science/datasets/nacti)).

**Comment by eap** [comment]
Thank you! I hadn't seen this.

**Comment by Nova-Scotia** [comment]
I should probably take a close look at it myself, I've been wondering whether there are any training images with a) two or more animals of the same species or b) two or more animals of different species present. I'm hoping to use my own images and just trying to figure out how strict to be in my filtering!

**Comment by dwwolfson** [comment]
@Nova-Scotia , there are images with more than one animal present, but there shouldn't be any images with multiple species.

**Comment by Nova-Scotia** [comment]
hey, thanks @dwwolfson!

**Comment by Nova-Scotia** [comment]
@eap , I don't think I am authorized to close this issue. Can you?

**Comment by mikeyEcology** [comment]
@Nova-Scotia I'm not sure if you're still after this, but while there are images with multiple individuals of the same species, they are not labeled as such in the image database. They are only labeled with the species present. 

@eap and for anyone else interested, all of the images from the paper are available for download from http://lila.science/datasets/nacti
