### ISSUE TITLE
Transferring trained models

### ISSUE THREAD

**Issue by VwakeM** [mikeyEcology/MLWIC#19]
I plan to retrain the default model on a computing cluster. What are the files associated with a trained MLWIC model and, how can I port the model back to my personal computer? 

I tested the `train()` function on my computer. The execution goes through fine without any error. But, the` log_dir_train` folder is empty.

**Comment by mikeyEcology** [comment]
If the log_dir_train folder is empty, something must have gone wrong. This is the folder that will contain the trained model, so you'll need to move the entire L1 folder (which will now contain your newly trained model). Can you please post your output when you trained?

Training on a cluster should work the same as training on a laptop. You'll need the L1 folder in some directory that you can specify. The only difference will be that since you are remoting in, you'll want to run a non-interactive session. Since you'll likely be running directly from Unix, you can specify `print_cmd=TRUE` to get the command that you can use in your script and run directly through Python, avoiding R (after you set up everything else you'll need in R). I don't know if this would actually speed anything up, though, because R is not loading anything into its memory for this function (which is what makes R slower). Do you have access to gpu's on this cluster? If so, you can specify the number that you want to use with `num_gpus`

**Comment by Nova-Scotia** [comment]
@mikeyEcology is it necessary to port the millions of images used to training to the computing cluster?

**Comment by mikeyEcology** [comment]
I think it would depend on what type of cluster you're using. If your cluster can access files on a local computer then you might not have to move them. However, you should consider that the model will need to access each image during the training process. If it is millions, then the time to locate images can make a big difference in the amount of time to train. Having them on the cluster will probably make training go a lot faster.

**Comment by Nova-Scotia** [comment]
Is this what you and coauthors did for the recent paper? Upload the NACTI dataset to a computing cluster and process everything there?

I just tried the training example on my computer (just CPU, I haven't figured out how to configure the code/programs to use GPU yet) and it took 4.7 hours for 2000 images... so... I will probably need a computing cluster, or a time machine!

**Comment by mikeyEcology** [comment]
Yes- we ran it on an HPC cluster at University of Wyoming. Training a model is going to be really slow on a standard computer. If you have access to a GPUs, you can specify the number of gpus with `num_gpus`. But how you run this will depend on the type of cluster you're using.

**Comment by VwakeM** [comment]
Thanks @mikeyEcology for debugging help and also instructions on using a computer cluster. I'm still dont have details on what the cluster will look like. It is with our research partners at UW-Madison. 

As for models not being created, I realized that our training dataset is not exactly similar to the datasets MLWIC was built on. This might be why the model was not created and I'm still investigating.

Our dataset has: 
1.	3 images/trigger
2.	Can have multiple classifications/trigger
3.	Can have multiple animals/trigger
4.	Can have multiple species/age classes/ trigger 

A trigger is basically one event when the camera's sensor is triggered and three pictures are taken in succession by our custom cameras. Do you any specific suggestions on training & classifying such data? If you have any information off hand, that would be great. But please don't feel compelled to answer these questions, as they are not advertised as features of the package. 

Appreciate the time you are taking to help out!

**Comment by mikeyEcology** [comment]
This shouldn't be a problem for training as long as you have the data structure is consistent with the `data_info` file described. However, in our package, you can only have one classification per image, so you would have to drop some of the information. \
It is possible to train such a model, but it would require a really large time investment on my part and I'm not able to give that much time at this point. I'm currently not getting paid for any work related to `MLWIC`, so I'm limited to what I can do in my spare time.

**Comment by VwakeM** [comment]
**Run no.1 with my data**

+ train( path_prefix = "C:\\Users\\mallevx\\Rcode\\AIClassify\\images\\", 
+        data_info = "C:\\Users\\mallevx\\Rcode\\AIClassify\\data_info_train.csv", 
+        model_dir = "C:\\Users\\mallevx\\Rcode\\AIClassify\\", 
+        python_loc = "C:\\Users\\mallevx\\Appdata\\Local\\Continuum\\anaconda3\\", 
+        num_classes = 14, delimiter = ",", depth = c(18, 34, 50, 101, 152), 
+        log_dir_train = "C:\\Users\\mallevx\\Rcode\\AIClassify\\model", 
+        retrain = FALSE, 
+        print_cmd = TRUE)
[1] "C:\\Users\\mallevx\\Appdata\\Local\\Continuum\\anaconda3\\python train.py --architecture resnet --depth 18 --path_prefix C:\\Users\\mallevx\\Rcode\\AIClassify\\images\\ --num_gpus 2 --batch_size 128 --data_info data_info_train.csv --delimiter , --num_classes 14 --log_dir C:\\Users\\mallevx\\Rcode\\AIClassify\\model" 
[2] "C:\\Users\\mallevx\\Appdata\\Local\\Continuum\\anaconda3\\python train.py --architecture resnet --depth 34 --path_prefix C:\\Users\\mallevx\\Rcode\\AIClassify\\images\\ --num_gpus 2 --batch_size 128 --data_info data_info_train.csv --delimiter , --num_classes 14 --log_dir C:\\Users\\mallevx\\Rcode\\AIClassify\\model" 
[3] "C:\\Users\\mallevx\\Appdata\\Local\\Continuum\\anaconda3\\python train.py --architecture resnet --depth 50 --path_prefix C:\\Users\\mallevx\\Rcode\\AIClassify\\images\\ --num_gpus 2 --batch_size 128 --data_info data_info_train.csv --delimiter , --num_classes 14 --log_dir C:\\Users\\mallevx\\Rcode\\AIClassify\\model" 
[4] "C:\\Users\\mallevx\\Appdata\\Local\\Continuum\\anaconda3\\python train.py --architecture resnet --depth 101 --path_prefix C:\\Users\\mallevx\\Rcode\\AIClassify\\images\\ --num_gpus 2 --batch_size 128 --data_info data_info_train.csv --delimiter , --num_classes 14 --log_dir C:\\Users\\mallevx\\Rcode\\AIClassify\\model"
[5] "C:\\Users\\mallevx\\Appdata\\Local\\Continuum\\anaconda3\\python train.py --architecture resnet --depth 152 --path_prefix C:\\Users\\mallevx\\Rcode\\AIClassify\\images\\ --num_gpus 2 --batch_size 128 --data_info data_info_train.csv --delimiter , --num_classes 14 --log_dir C:\\Users\\mallevx\\Rcode\\AIClassify\\model"

**Run no.2 with MLWIC_example**

train(path_prefix = "C:\\Users\\mallevx\\Rcode\\AIClassify\\MLWIC_examples-master\\images", # this is the absolute path to the images. 
+       data_info = "C:\\Users\\mallevx\\Rcode\\AIClassify\\MLWIC_examples-master\\data_info_train.csv", # this is the location of the csv containing image information. It has Unix linebreaks and no headers.
+       model_dir = "C:\\Users\\mallevx\\Rcode\\AIClassify", # assuming this is where you stored the L1 folder in Step 3 of the instructions: github.com/mikeyEcology/MLWIC/blob/master/README
+       python_loc = "C:\\Users\\mallevx\\Appdata\\Local\\Continuum\\anaconda3\\", # the location of Python on your computer. 
+       num_classes = 28, # this is the number of species from our model. When you train your own model, you will replace this with the number of species/groups of species in your dataset
+       log_dir_train = "training_output" # this will be a folder that contains the trained model (call it whatever you want). You will specify this folder as the "log_dir" when you classify images using this trained model. For example, the log_dir for the model included in this package is called "USDA182"
+ )
Traceback (most recent call last):
  File "train.py", line 339, in <module>
    main()
  File "train.py", line 319, in main
    args.num_samples = sum(1 for line in open(args.data_info))
FileNotFoundError: [Errno 2] No such file or directory: 'data_info_train.csv'
[1] "training of model took 5.58821606636047 secs. The trained model is in training_output. Specify this directory as the log_dir when you use classify(). "
>

**Comment by VwakeM** [comment]
Thanks @mikeyEcology! Agree with you. We are making some progress with gaining access to a computing cluster, so I'll keep you posted. 

Above are the results of running the train function for two scenarios. The folder structures and file names are similar, but the results are different. Run no.1 does not give any output while no.2 errors out.

**Comment by mikeyEcology** [comment]
I'm assuming you already checked to ensure that you have the data info file in C:\\Users\\mallevx\\Rcode\\AIClassify\\?
Some other things to try:
1) You can only train one model at a time and when you specified `depth`, this is to train 5 models at a time. I would start with `depth=18` and then increase depth if the model is a bad fit. 
2) Switch your slashes to look like C:/Users/mallevx/... I don't know why this would make a difference, but it could.

**Comment by VwakeM** [comment]
Thank you! I'll try that out.
