### ISSUE TITLE
number of GPUs

### ISSUE THREAD

**Issue by oliviergimenez** [mikeyEcology/MLWIC#25]
Hi,

First I'd like to congratulate @mikeyEcology on such an amazing and useful tool 💯 Thank you!

I'm training a model then would like to use it to classify some pictures I have. Everything goes well when I train the model with 10 pix. It takes approx 10 minutes on my Mac using CPU (num_gpus = 2 as described in the help file). Now I'd like to go for 2000 pix per species (15 species in total), which would take ages with CPU.

I'm considering using GPUs but cannot find guidelines to amend the num_gpus. Apologies in advance if my question is naive. How many GPUs can I use? I have a NVIDIA GeForce GT 750M. 

Cheers,
Olivier

**Comment by mikeyEcology** [comment]
Thank you. There is no limit to the number of gpus you can use for the function, but it will be limited by the number on your machine. For your NVIDIA chip it will depend on how you have it configured, but it is likely one gpu. So you can specify this when you run `train` with `num_gpus=1`.

**Comment by oliviergimenez** [comment]
Thanks for your speedy response, I will do that.

**Comment by oliviergimenez** [comment]
Thanks for your speedy response, I will do that.
