### ISSUE TITLE
Model Trained for African Wildlife

### ISSUE THREAD

**Issue by pirocha** [mikeyEcology/MLWIC#29]
Hi!
I am trying to apply MLWIC in a camera-trapping project we are running in southern Angola. I finally managed to successfully run the classify command on the examples the authors provide and I'm now in the point of training the model for my species. I have around 200 000 pictures already classified, but I'm afraid it won't be enough to properly train the models, especially in the rarer species.
I would like to ask if anyone has a model trained in African wildlife that could share.

Thank you very much!

**Comment by mikeyEcology** [comment]
If you'd like to add classified images to your training dataset, the [Snapshot Serengeti dataset](http://lila.science/datasets/snapshot-serengeti) contains millions of classified images of wildlife from Africa.

**Comment by pirocha** [comment]
Thank you @mikeyEcology! It will be very useful...
