### ISSUE TITLE
Failed `setup()` requires manual removal of r-reticulate environment

### ISSUE THREAD

**Issue by MikeCIDFG** [mikeyEcology/MLWIC#3]
If running `setup()` fails, you have to manually remove the created `r-reticulate` conda environment from `/anaconda2/envs`

The conda environment name is hard-coded in `setup.R`, and it doesn't check whether an env with that name already exists before trying to run `conda create -n r-reticulate`. 

Consequently, subsequent attempts to run `setup()` will fail even after fixing whatever error caused the initial `setup()` failure, or else you have to keep manually removing the previously created environment.

**Comment by mikeyEcology** [comment]
Thank you for finding this error. I edited the function. Let me know if you still have problems with it.

**Comment by MikeCIDFG** [comment]
Perfect - identifies env & removes all packages before recreating!
