### ISSUE TITLE
Eval.py not found

### ISSUE THREAD

**Issue by zbell44** [mikeyEcology/MLWIC#36]
Hi,

Hopefully someone can help with this issue. I've tried setting up this software numerous times on Ubuntu18 and Windows10 and have run into the same issue. Setup proceeds normally compared to others' installations, but classify produces the following error: "can't open file 'eval.py': [Errno 2] No such file or directory". My understanding is that eval.py is a script that should be included with tensorflow and that the python file should point to this file?

Thanks

**Comment by mikeyEcology** [comment]
Hi @zbell44 The function isn't finding your L1 folder that you downloaded and stored in Step 3 of setup. You should specify this as your `model_dir` when running `classify`
