### ISSUE TITLE
setup() fails with UnsatisfiableError: The following specifications were found to be in conflict:   - argparse   - tensorflow

### ISSUE THREAD

**Issue by hannaboe** [mikeyEcology/MLWIC#7]
Hei, 
After installing tensorflow I was running setup() but got an error/warning message and it seems like there are problems with installing 'tensorflow' and 'argparse'. I'm quite new to python but to me it looks like the packages require different dependencies and thus can not be installed together. I'm using a windows machine but had the same problem when trying to run it on a Linux machine or installing the packages with anaconda. 
I always go something like that:
UnsatisfiableError: The following specifications were found to be in conflict:
  - argparse
  - tensorflow

That is the output I got when running setup():
> setup(python_loc =  "C:/Users/hbo042/AppData/Local/Continuum/anaconda3")

Remove all packages in environment C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\envs\r-reticulate:

## Package Plan ##

  environment location: C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\envs\r-reticulate

The following packages will be REMOVED:

    certifi:        2018.10.15-py37_0     
    pip:            18.1-py37_0           
    python:         3.7.1-h33f27b4_4      
    setuptools:     40.5.0-py37_0         
    vc:             14.1-h0510ff6_4       
    vs2015_runtime: 14.15.26706-h3a45250_0
    wheel:          0.32.2-py37_0         
    wincertstore:   0.2-py37_0            

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\envs\r-reticulate

  added / updated specs: 
    - python

The following NEW packages will be INSTALLED:

    certifi:        2018.10.15-py37_0     
    pip:            18.1-py37_0           
    python:         3.7.1-h33f27b4_4      
    setuptools:     40.5.0-py37_0         
    vc:             14.1-h0510ff6_4       
    vs2015_runtime: 14.15.26706-h3a45250_0
    wheel:          0.32.2-py37_0         
    wincertstore:   0.2-py37_0            

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use:
# > activate r-reticulate
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#
Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - argparse
  - tensorflow
Use "conda info <package>" to see the dependencies for each package.

Error: Error 1 occurred installing packages into conda environment r-reticulate
In addition: Warning message:
running command '"C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\Scripts\conda.exe" "install" "-c" "conda-forge" "--yes" "--name" "r-reticulate" "numpy" "cycler" "matplotlib" "tornado" "argparse" "six" "scipy" "tensorflow"' had status 1 

Thank you, 
Hanna

**Comment by mikeyEcology** [comment]
This error is expected. You can ignore it and try running `classify` on the example images.

**Comment by hannaboe** [comment]
Sorry for that question, classify did not work and I tried to figure out why. 
After reinstalling anaconda and copying and renaming the data_info file manually (the cp command did not work), classify seemed to run better than before. However, I still don't get the model-prediction-file.

I get the following output when I run classify:

classify(path_prefix = "C:/Users/hbo042/Documents/MLWIC/MLWIC_examples-master/images", # this is the absolute path to the images. 
         data_info = "C:/Users/hbo042/Documents/MLWIC/MLWIC_examples-master/image_labels.csv", # this is the location of the csv containing image information. It has Unix linebreaks and no headers.
         model_dir = "C:/Users/hbo042/Documents/MLWIC", # assuming this is where you stored the L1 folder in Step 3 of the instructions: github.com/mikeyEcology/MLWIC/blob/master/README
         python_loc = "C:/Users/hbo042/AppData/Local/Continuum/anaconda3/", # the location of Python on your computer. 
         save_predictions = "model_predictions.txt") # this is the default and you should use it unless you have reason otherwise.

WARNING:tensorflow:From C:\Users\hbo042\Documents\MLWIC\L1\data_loader.py:31: slice_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(tuple(tensor_list)).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\input.py:372: range_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.range(limit).shuffle(limit).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\input.py:318: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
WARNING:tensorflow:From C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\input.py:188: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
WARNING:tensorflow:From C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\input.py:197: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\training\input.py:197: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From C:\Users\hbo042\Documents\MLWIC\L1\data_loader.py:63: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
tf.estimator package not installed.
tf.estimator package not installed.
Namespace(architecture='resnet', batch_size=128, crop_size=[224, 224], data_info='data_info.csv', delimiter=',', depth=18, load_size=[256, 256], log_dir='USDA182', num_batches=16, num_channels=3, num_classes=28, num_samples=1933, num_threads=20, path_prefix='C:/Users/hbo042/Documents/MLWIC/MLWIC_examples-master/images', save_predictions='model_predictions.txt', top_n=5)
Filling queue with 2000 images before starting to train. This may take some times.
Traceback (most recent call last):
  File "eval.py", line 129, in <module>
    main()
  File "eval.py", line 125, in main
    evaluate(args)
  File "eval.py", line 31, in evaluate
    logits = arch.get_model(images, 0.0, False, args)
  File "C:\Users\hbo042\Documents\MLWIC\L1\arch.py", line 12, in get_model
    return architectures.resnet.inference(inputs, args.depth, args.num_classes, wd, is_training)
  File "C:\Users\hbo042\Documents\MLWIC\L1\architectures\resnet.py", line 24, in inference
    return getModel(x, num_output, wd, is_training, num_blocks= num_blocks, bottleneck= bottleneck)
  File "C:\Users\hbo042\Documents\MLWIC\L1\architectures\resnet.py", line 32, in getModel
    x = spatialConvolution(x, 7, 2, 64, weight_initializer= conv_weight_initializer, wd= wd)
  File "C:\Users\hbo042\Documents\MLWIC\L1\architectures\common.py", line 105, in spatialConvolution
    shape, weight_initializer, tf.contrib.layers.l2_regularizer(wd))
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\__init__.py", line 48, in <module>
    from tensorflow.contrib import distribute
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\distribute\__init__.py", line 34, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\distribute\python\tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\tpu\__init__.py", line 73, in <module>
    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\contrib\tpu\python\tpu\keras_support.py", line 71, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\estimator\__init__.py", line 25, in <module>
    import tensorflow.python.estimator.estimator_lib
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\estimator\estimator_lib.py", line 41, in <module>
    from tensorflow.python.estimator.inputs import inputs
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\estimator\inputs\inputs.py", line 22, in <module>
    from tensorflow.python.estimator.inputs.numpy_io import numpy_input_fn
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\estimator\inputs\numpy_io.py", line 26, in <module>
    from tensorflow.python.estimator.inputs.queues import feeding_functions
  File "C:\Users\hbo042\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\estimator\inputs\queues\feeding_functions.py", line 40, in <module>
    import pandas as pd
  File "C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\pandas\__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\pandas\core\api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\pandas\core\groupby\__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\pandas\core\groupby\groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\pandas\core\frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "C:\Users\hbo042\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\pandas\core\series.py", line 67, in <module>
    import pandas.core.ops as ops
AttributeError: module 'pandas' has no attribute 'core'
[1] "evaluation of images took 3.78462910652161 secs. The results are stored in C:/Users/hbo042/Documents/MLWIC/L1/model_predictions.txt. To view the results in a viewer-friendly format, please use the function make_output"
Warning messages:
1: running command 'cp C:/Users/hbo042/Documents/MLWIC/MLWIC_examples-master/image_labels.csv C:/Users/hbo042/Documents/MLWIC/L1/data_info.csv' had status 127 
2: running command 'C:/Users/hbo042/AppData/Local/Continuum/anaconda3/python eval.py --architecture resnet --depth 18 --log_dir USDA182 --path_prefix C:/Users/hbo042/Documents/MLWIC/MLWIC_examples-master/images --batch_size 128 --data_info data_info.csv --delimiter , --save_predictions model_predictions.txt --num_classes=28
' had status 1

**Comment by mikeyEcology** [comment]
I'm not sure what exactly went wrong for you, but if `cp` isn't working on your computer, then you may have some sort of permission issue with your directories. Are you the Windows administrator on your computer? Can you try running an experiment to see if `cp` works on other files in your computer?

**Comment by hannaboe** [comment]
I'm not the administrator but normally have administrator rights.
`cp` does also not work on other files. I tried to run it directly in the command prompt but I says: 
'cp' is not recognized as an internal or external command,
operable program or batch file.

However if I use 'copy' instead of 'cp' it works. And if I used `shell("copy...")` instead of `system("copy...")` in R, it works as well.

**Comment by kow10120** [comment]
I've been able to successfully use MLWIC on Mac OSx, but I am unable to use `setup` on Windows. From what I see on Tensorflow's installation webpage, Tensorflow requires python version 3.4, 3.5, or 3.6. 

When running `setup` and setting the `r_reticultate =` to FALSE I notice that it installs python 3.7

```
The following NEW packages will be INSTALLED:

certifi:        2018.10.15-py37_0     
pip:            18.1-py37_0           
python:         3.7.1-h33f27b4_4      
setuptools:     40.5.0-py37_0         
vc:             14.1-h0510ff6_4       
vs2015_runtime: 14.15.26706-h3a45250_0
wheel:          0.32.2-py37_0         
wincertstore:   0.2-py37_0            
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
```

Is this an issue for Windows users?
