### ISSUE TITLE
Issue with classify() function.

### ISSUE THREAD

**Issue by VwakeM** [mikeyEcology/MLWIC#8]
I had the same issue with setup() as reported in: https://github.com/mikeyEcology/MLWIC/issues/7. 
So, I installed tensorflow separately. 

I then went ahead to test the classify() function using MLWIC example. I get the following error: 

/anaconda3/bin/python: can't open file 'eval.py': [Errno 2] No such file or directory
-----------------------------------------------------------------------------------------------------------
Environment details:

- I'm running MLWIC from RStudio server on Centos 7 operating system.
- Python version is 3.6.5
- R is 3.5.1
- tensorflow is 1.12.0 

Please let me know if additional details are required. Thanks!

**Comment by mikeyEcology** [comment]
Can you please post the code you put into `classify` and copy the output that came in your R console?

**Comment by VwakeM** [comment]
**Code for classify():** 

classify(path_prefix = "/home/zuckerberg/images", # this is the absolute path to the images. 
         data_info = "/home/zuckerberg/image_labels.csv", # this is the location of the csv containing image information. It has Unix linebreaks and no headers.
         model_dir = "/home/zuckerberg", # assuming this is where you stored the L1 folder in Step 3 of the instructions: github.com/mikeyEcology/MLWIC/blob/master/README
         python_loc = "~/anaconda3/bin/", # the location of Python on your computer. 
         save_predictions = "model_predictions.txt" # this is the default and you should use it unless you have reason otherwise.
)


**Console output:**

classify(path_prefix = "/home/zuckerberg/images", # this is the absolute path to the images. 
 data_info = "/home/zuckerberg/image_labels.csv", # this is the location of the csv containing image information. It has Unix linebreaks and no headers.
  model_dir = "/home/zuckerberg", # assuming this is where you stored the L1 folder in Step 3 of the instructions: github.com/mikeyEcology/MLWIC/blob/master/README
  python_loc = "~/anaconda3/bin/", # the location of Python on your computer. 
         save_predictions = "model_predictions.txt" # this is the default and you should use it unless you have reason otherwise.
 )
/home/zuckerberg/anaconda3/bin/python: can't open file 'eval.py': [Errno 2] No such file or directory
[1] "evaluation of images took 0.0387463569641113 secs. The results are stored in /home/zuckerberg/L1/model_predictions.txt. To view the results in a viewer-friendly format, please use the function make_output"

**Comment by mikeyEcology** [comment]
For some reason it's not finding the L1 directory on your machine. I assume you have store it in /home/zuckerberg ? Also, you might try deleting the "~" in your python_loc, so it would read `python_loc = "~/anaconda3/bin/"`. I doubt this would cause the problem though.

**Comment by VwakeM** [comment]
Yeah, the previous issue was with the folder structure. I had an L1 folder inside another L1 folder. On correcting that, I get the following error on running classify(): 

**2018-12-12 10:28:24.295189: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.**

I am guessing this is something to do with CentOS and Tensorflow installation itself. Please close the issue as it has nothing to do with the MLWIC package itself. Thanks a lot for your help!

**Comment by mikeyEcology** [comment]
I'm glad you got it figured out. This error message will occur whenever you run tensorflow, but check the output, because this usually means that it worked.
