### ISSUE TITLE
classify function "cp" error

### ISSUE THREAD

**Issue by 0106WeiWeiDeng** [mikeyEcology/MLWIC#9]
setwd("E:/test_for_mlwic/")
> classify(path_prefix = paste0(getwd(), "/images"), data_info = paste0(getwd(), "/image_labels.csv"), model_dir = getwd(), save_predictions = "model_predictions.txt", python_loc = "D:/anaconda3_52/", num_classes = 28, delimiter = ",", architecture = "resnet", depth = "18", log_dir = "USDA182")
D:\anaconda3_52\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "eval.py", line 129, in <module>
    main()
  File "eval.py", line 116, in main
    args.num_samples = sum(1 for line in open(args.data_info))
FileNotFoundError: [Errno 2] No such file or directory: 'data_info.csv'
[1] "evaluation of images took 31.287257194519 secs. The results are stored in E:/test_for_mlwic/L1/model_predictions.txt. To view the results in a viewer-friendly format, please use the function make_output"
Warning messages:
1: running command 'cp E:/test_for_mlwic/image_labels.csv E:/test_for_mlwic/L1/data_info.csv' had status 127 
2: running command 'D:/anaconda3_52/python eval.py --architecture resnet --depth 18 --log_dir USDA182 --path_prefix E:/test_for_mlwic/images --batch_size 128 --data_info data_info.csv --delimiter , --save_predictions model_predictions.txt --num_classes=28
' had status 1

****hi,
It seems like a error with "cp", how to fix it**
My system is windows 10, R version is 3.4.1 RC, anaconda version is anaconda3-5.2, tensorflow version is 1.12, cpu-only.
The reason for this error is that "cp" is UNIX command, it can not work on windows?**

**Comment by 0106WeiWeiDeng** [comment]
setup  function in MLWIC will download python 3.7, but python 3.7 doesn't support tensorflow, this may cause above error

**Comment by 0106WeiWeiDeng** [comment]
I am trying to use this R package in Centos 7...

**Comment by 0106WeiWeiDeng** [comment]
> I am trying to use this R package in Centos 7...

It can run on CentOS 7, so I think this package can only run on UNIX-like system

**Comment by mikeyEcology** [comment]
I'm glad you got it running on CentOS. It will certainly run better on UNIX and LINUX systems. Many people are getting this to work on Windows, but you're not the first to have issues with `cp`. `cp` should work in the command line of Windows computers, and when it doesn't there is likely something else wrong with the computer.
